name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SDL_VIDEODRIVER: "dummy"
  SDL_AUDIODRIVER: "disk"
  RUSTFLAGS: -D missing_docs -D warnings

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Alsa lib
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Build
        run: |
          cargo check
          cargo build

      - name: Lint
        run: |
          cargo fmt -- --check --color always
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo nextest run --hide-progress-bar --failure-output final --no-tests warn
